aliases:
  - &restore-cache
    keys:
      - v2-dependencies-{{ .Branch }}-{{ checksum "yarn.lock" }}
      # Fallback in case checksum fails
      - v2-dependencies-{{ .Branch }}-
  - &save-cache
    paths:
      - node_modules
    key: v2-dependencies-{{ .Branch }}-{{ checksum "yarn.lock" }}

version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore-cache: *restore-cache
      - run: yarn --no-progress --frozen-lockfile
      - save-cache: *save-cache

  test-node-8:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore-cache: *restore-cache
      - run: yarn --no-progress --frozen-lockfile
      - save-cache: *save-cache
      - run:
          command: yarn test
  test-node-9:
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      - restore-cache: *restore-cache
      - run: yarn --no-progress --frozen-lockfile
      - save-cache: *save-cache
      - run:
          command: yarn test
  test-node-10:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore-cache: *restore-cache
      - run: yarn --no-progress --frozen-lockfile
      - save-cache: *save-cache
      - run:
          command: yarn test

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - test-node-8:
          requires:
            - build
      - test-node-9:
          requires:
            - build
      - test-node-10:
          requires:
            - build
