aliases:
  - &restore-cache
    keys:
      - v2-dependencies-{{ .Branch }}-{{ checksum "yarn.lock" }}
      # Fallback in case checksum fails
      - v2-dependencies-{{ .Branch }}-
  - &save-cache
    paths:
      - node_modules
    key: v2-dependencies-{{ .Branch }}-{{ checksum "yarn.lock" }}
  - &docker-settings
      - image: circleci/node:10.16.1

version: 2
jobs:
  build:
    docker: *docker-settings
    steps:
      - checkout
      - restore-cache: *restore-cache
      - run: yarn --no-progress --frozen-lockfile
      - save-cache: *save-cache

  test-node-10:
    docker: *docker-settings
    steps:
      - checkout
      - restore-cache: *restore-cache
      - run: yarn --no-progress --frozen-lockfile
      - save-cache: *save-cache
      - run:
          command: yarn test

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - test-node-10:
          requires:
            - build
